// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/sqkam/sensitivecrawler/ioc"
	"github.com/sqkam/sensitivecrawler/pkg/sensitivecrawler"
)

// Injectors from wire.go:

func InitSensitiveCrawler() sensitivecrawler.Service {
	config := ioc.InitConfig()
	sensitiveMatcher := ioc.InitSensitiveMatcher(config)
	service := sensitivecrawler.NewDefaultService(config, sensitiveMatcher)
	return service
}
